Fishery/Areas/Admin/Controllers/BoatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Fishery.Models;
using Microsoft.AspNetCore.Mvc;

namespace Fishery.Areas.Admin.Controllers
{
    public class BoatController : Controller
    {
        private readonly FisheryContext _context;

        public BoatController(FisheryContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var model = _context.Boat.ToList();
            return View(model);
        }

        public IActionResult Edit(int id)
        {
            return View(_context.Boat.Find(id));
        }

        public IActionResult Create()
        {
            return View("~/Areas/Admin/Views/Boat/Edit.cshtml", new Boat());
        }

        [HttpPost]
        public IActionResult Save(Boat model)
        {
            if (ModelState.IsValid)
            {
                _context.Boat.Update(model);
                _context.SaveChanges();
            }
            else
            {
                return View("~/Areas/Admin/Views/Boat/Edit.cshtml", model);
            }
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            _context.Boat.Remove(_context.Boat.Find(id));
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Fishery/Areas/Admin/Controllers/FoodController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Fishery.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Fishery.Areas.Admin.Controllers
{
    public class FoodController : Controller
    {
        private readonly IWebHostEnvironment _env;
        private readonly FisheryContext _context;

        public FoodController(IWebHostEnvironment env, FisheryContext context)
        {
            _env = env;
            _context = context;
        }

        /// <summary>
        /// 預設是餐廳管理
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            var model = _context.Food.OrderBy(a => a.Seq).ToList();
            return View(model);
        }

        public IActionResult Edit(int id)
        {
            var model = _context.Food.Find(id);
            return View(new FoodPageModel() { food = model });
        }

        public IActionResult Create()
        {
            return View("~/Areas/Admin/Views/Food/Edit.cshtml",new FoodPageModel() { food = new Food() { Id = 0} });
        }

        [HttpPost]
        public IActionResult Save(FoodPageModel model)
        {
            if (ModelState.IsValid)
            {
                var food = _context.Food.Find(model.food.Id);
                if (model.food.Id != 0)
                {
                    if (food == null) return Content("資料錯誤");
                    else
                    {
                        food.Name = model.food.Name;
                        food.Desc = model.food.Desc;
                        food.Seq = model.food.Seq;
                        food.UpdateTime = DateTime.Now;
                    }
                }
                else
                {
                    food = model.food;
                    food.UpdateTime = DateTime.Now;
                    _context.Food.Add(food);
                }

                if (model.coverImage != null)
                {
                    //有選擇檔案, 先檢查檔名
                    string filename = model.coverImage.FileName;
                    var targetFile = Path.Combine(_env.WebRootPath, "images", "foods", model.coverImage.FileName);
                    int index = 1;

                    while (System.IO.File.Exists(targetFile))
                    {
                        //改名改到不同名稱為止
                        filename = String.Format("{0}_{1}.{2}",
                            Path.GetFileNameWithoutExtension(model.coverImage.FileName),
                            index,
                            Path.GetExtension(model.coverImage.FileName));
                        targetFile = Path.Combine(_env.WebRootPath, "images", "foods", filename);
                        index++;
                    }
                    model.coverImage.CopyTo(new FileStream(targetFile, FileMode.Create));
                    model.food.Cover = filename;
                    food.Cover = filename;
                }
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View("~/Areas/Admin/Views/Food/Edit.cshtml", model.food.Id);
        }

        /// <summary>
        /// 列出指定餐廳的菜單
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult Menu(int id)
        {
            var food = _context.Food.Find(id);
            if (food == null)
            {
                return Content("輸入錯誤");
            }
            ViewData["name"] = food.Name;
            ViewData["foodid"] = food.Id;
            var menu = _context.FoodMenu.Where(a => a.FoodId == id).ToList();

            return View(menu);
        }

        public IActionResult MenuEdit(int id)
        {
            var menu = _context.FoodMenu.Find(id);
            if (menu == null) return Content("資料錯誤.");

            FoodMenuPageModel model = new FoodMenuPageModel()
            {
                 menu = menu
            };
            return View(model);
        }

        public IActionResult MenuCreate(int id)
        {
            FoodMenuPageModel model = new FoodMenuPageModel() { 
                menu = new FoodMenu() { 
                     Id = 0,
                     FoodId = id
                }
            };
            return View("~/Areas/Admin/Views/Food/MenuEdit.cshtml", model);
        }

        public IActionResult MenuSave(FoodMenuPageModel model)
        {
            if (ModelState.IsValid)
            {
                var menu = _context.FoodMenu.Find(model.menu.Id);
                if (model.menu.Id != 0)
                {
                    if (menu == null) return Content("資料錯誤");
                    else
                    {
                        menu.Name = model.menu.Name;
                        menu.Desc = model.menu.Desc;
                    }
                }
                else
                {
                    menu = model.menu;
                    _context.FoodMenu.Add(menu);
                }


                if (model.pic != null)
                {
                    //有選擇檔案, 先檢查檔名
                    string filename = model.pic.FileName;
                    var targetFile = Path.Combine(_env.WebRootPath, "images", "foods", model.pic.FileName);
                    int index = 1;

                    while (System.IO.File.Exists(targetFile))
                    {
                        //改名改到不同名稱為止
                        filename = String.Format("{0}_{1}.{2}",
                            Path.GetFileNameWithoutExtension(model.pic.FileName),
                            index,
                            Path.GetExtension(model.pic.FileName));
                        targetFile = Path.Combine(_env.WebRootPath, "images", "foods", filename);
                        index++;
                    }
                    model.pic.CopyTo(new FileStream(targetFile, FileMode.Create));
                    model.menu.Pic1 = filename;
                    menu.Pic1 = filename;
                }
                _context.SaveChanges();
                return RedirectToAction(actionName: "Menu", routeValues: new { id = model.menu.FoodId });
            }
            else
            { 
                return View("~/Areas/Admin/Views/Food/MenuEdit.cshtml", model); 
            }
            
        }

        public IActionResult Delete(int id)
        {
            // 先刪除所有菜單
            _context.FoodMenu.RemoveRange(_context.FoodMenu.Where(a => a.FoodId == id));
            _context.Food.Remove(_context.Food.Find(id));
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult MenuDelete(int id)
        {
            _context.FoodMenu.Remove(_context.FoodMenu.Find(id));
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

    }

    public class FoodPageModel
    {
        public Food food { get; set; }
        public IFormFile coverImage { set; get; }
    }

    public class FoodMenuPageModel
    { 
        public FoodMenu menu { get; set; }

        public IFormFile pic { get; set; }
    }
}

Fishery/Areas/Admin/Controllers/ScenicController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Fishery.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Fishery.Areas.Admin.Controllers
{
    public class ScenicController : Controller
    {
        private readonly IWebHostEnvironment _env;
        private readonly FisheryContext _context;

        public ScenicController(IWebHostEnvironment env, FisheryContext context)
        {
            _env = env;
            _context = context;
        }

        public IActionResult Index()
        {
            return View(_context.ScenicSpot.ToList());
        }

        public IActionResult Edit(int id)
        {
            return View(new ScenicPageModel() { ScenicSpot = _context.ScenicSpot.Find(id) });
        }

        public IActionResult Create()
        {
            return View("~/Areas/Admin/Views/Scenic/Edit.cshtml", 
                new ScenicPageModel() { ScenicSpot = new ScenicSpot() { Id = 0 } });
        }

        public IActionResult Save(ScenicPageModel model) 
        {
            if (ModelState.IsValid)
            {
                var scenicSpot = _context.ScenicSpot.Find(model.ScenicSpot.Id);
                if (model.ScenicSpot.Id != 0)
                {
                    if (scenicSpot == null) return Content("資料錯誤");
                    else
                    {
                        scenicSpot.Name = model.ScenicSpot.Name;
                        scenicSpot.Desc = model.ScenicSpot.Desc;
                        scenicSpot.Seq = model.ScenicSpot.Seq;
                        scenicSpot.UpdateTime = DateTime.Now;
                    }
                }
                else
                {
                    scenicSpot = model.ScenicSpot;
                    scenicSpot.UpdateTime = DateTime.Now;
                    _context.ScenicSpot.Add(scenicSpot);
                }

                HandleUploadImage(model, scenicSpot, "Cover");
                HandleUploadImage(model, scenicSpot, "Pic1");
                HandleUploadImage(model, scenicSpot, "Pic2");
                HandleUploadImage(model, scenicSpot, "Pic3");

                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View("~/Areas/Admin/Views//Edit.cshtml", model.ScenicSpot.Id);
        }

        private void HandleUploadImage(ScenicPageModel model, ScenicSpot scenicSpot, string PropertyName)
        {
            var iFormFile = (IFormFile)GetPropValue(model, PropertyName);
            if (iFormFile != null)
            {
                //有選擇檔案, 先檢查檔名
                string filename = iFormFile.FileName;
                var targetFile = Path.Combine(_env.WebRootPath, "images", "scenics", iFormFile.FileName);
                int index = 1;

                while (System.IO.File.Exists(targetFile))
                {
                    //改名改到不同名稱為止
                    filename = String.Format("{0}_{1}.{2}",
                        Path.GetFileNameWithoutExtension(iFormFile.FileName),
                        index,
                        Path.GetExtension(iFormFile.FileName));
                    targetFile = Path.Combine(_env.WebRootPath, "images", "scenics", filename);
                    index++;
                }
                iFormFile.CopyTo(new FileStream(targetFile, FileMode.Create));

                // 這邊要剛好 PageModel 裡面的 IFormFile 屬性名稱 與 ScenicSpot裡面的一樣
                SetPropValue(model.ScenicSpot, PropertyName, filename);

                SetPropValue(scenicSpot, PropertyName, filename);
            }
        }

        public static object GetPropValue(object src, string propName)
        {
            return src.GetType().GetProperty(propName).GetValue(src, null);
        }

        public static void SetPropValue(object src, string propName, object value)
        {
            src.GetType().GetProperty(propName).SetValue(src, value);
        }

        public IActionResult Delete(int id)
        {
            _context.ScenicSpot.Remove(_context.ScenicSpot.Find(id));
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

    }

    public class ScenicPageModel
    { 
        public ScenicSpot ScenicSpot { get; set; }
        public IFormFile Cover { get; set; }
        public IFormFile Pic1 { get; set; }
        public IFormFile Pic2 { get; set; }
        public IFormFile Pic3 { get; set; }

    }
}

Fishery/Areas/Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;

namespace Fishery.Areas.Admin.Controllers
{
    public class UserController : Controller
    {
        public IActionResult Index(LoginModel model)
        {
            if (User.Identity.IsAuthenticated) return RedirectToAction(actionName: "Index", controllerName: "Home");

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.Account == "admin" && model.Password == "admin")
                {
                    var claims = new List<Claim>();

                    claims.Add(new Claim(ClaimTypes.NameIdentifier, model.Account));
                    claims.Add(new Claim(ClaimTypes.Name, "管理者"));

                    await HttpContext.SignInAsync(
                        CookieAuthenticationDefaults.AuthenticationScheme,
                        new ClaimsPrincipal(
                            new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme, ClaimTypes.NameIdentifier, ClaimTypes.Role)));
                    return RedirectToAction(actionName: "Index", controllerName: "Food");
                }
                else
                {
                    ModelState.AddModelError("Account", "帳號不存在或密碼不正確");
                    return View("~/Areas/Admin/Views/User/Index.cshtml", model);
                }

            }
            else
            {
                return View("~/Areas/Admin/Views/User/Index.cshtml", model);
            }
        }

        public async Task<IActionResult> LogoutAsync()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Index");
        }

        public class LoginModel
        {
            [Required(ErrorMessage = "{0}必填")]
            [Display(Name = "帳號")]
            public string Account { get; set; }
            [Required(ErrorMessage = "{0}必填")]
            [Display(Name = "密碼")]
            public string Password { get; set; }
        }
    }
}

Fishery/Areas/Admin/Views/Shared/_Layout.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>簡易後台管理系統</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/lib/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bbootstrap 4 -->
    <link rel="stylesheet" href="~/lib/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/lib/admin-lte/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/lib/overlayscrollbars/css/OverlayScrollbars.min.css">
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        
        .content-wrapper {
            background: white;
        }
    </style>
</head>

<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
            </ul>
        </nav>

        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
    with font-awesome or any other icon font library -->
                        <li class="nav-header">功能列表</li>
                        <li class="nav-item">
                            <a asp-controller="Home" asp-action="Index" class="nav-link">
                                <i class="nav-icon  fas fa-table"></i>
                                <p>
                                    跑馬燈與輪播
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Food" asp-action="Index" class="nav-link">
                                <i class="nav-icon  fas fa-table"></i>
                                <p>
                                    餐廳管理
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Scenic" asp-action="Index" class="nav-link">
                                <i class="nav-icon  fas fa-table"></i>
                                <p>
                                    景點管理
                                </p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a asp-controller="Boat" asp-action="Index" class="nav-link">
                                <i class="nav-icon  fas fa-users-cog"></i>
                                <p>
                                    船班管理
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="User" asp-action="Logout" class="nav-link">
                                <i class="nav-icon fas fa-sign-out"></i>
                                <p>
                                    登出
                                </p>
                            </a>
                        </li>
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark">@ViewData["Title"]</h1>
                        </div><!-- /.col -->
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                @RenderSection("breadcrumb", required: false)
                            </ol>
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->
            <!-- Main content -->
            <section class="content">
                @RenderBody()
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <strong>

            </strong>
        </footer>
        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/lib/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="~/lib/jqueryui/jquery-ui.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="~/lib/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Fishery/Areas/Admin/Views/Shared/_LoginLayout.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>簡易後台管理系統</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/lib/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bbootstrap 4 -->
    <link rel="stylesheet" href="~/lib/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/lib/admin-lte/css/adminlte.min.css">
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        @@media(min-width: 768px) {
            body:not(.sidebar-mini-md) .content-wrapper, body:not(.sidebar-mini-md) .main-footer, body:not(.sidebar-mini-md) .main-header {
                margin: 0 3rem;
            }
        }

        .content-wrapper {
            background: white;
        }
    </style>
</head>

<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark">@ViewData["Title"]</h1>
                        </div><!-- /.col -->
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                @RenderSection("breadcrumb", required: false)
                            </ol>
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->
            <!-- Main content -->
            <section class="content">
                @RenderBody()
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <strong>
                
            </strong>
        </footer>
        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/lib/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="~/lib/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <script src="~/js/site.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>